FROM ubuntu:18.04
LABEL maintainer="Timo Runge"

ARG ansible_role=${ansible_role}
ARG ansible_version=${ansible_version}
ARG TRAVIS=${TRAVIS}

ENV ansible_role=${ansible_role}
ENV travis=${TRAVIS}

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    curl \
    python \
    python-apt \
    python-pip \
    systemd \
    unzip \
    wget
RUN apt-get clean

RUN pip install --upgrade pip setuptools
RUN pip install ansible=="${ansible_version}"
RUN pip install ansible-lint coverage junit-xml splitter
RUN ansible --version

ENTRYPOINT [ "/docker/docker-entrypoint.sh" ]
