FROM centos:7
LABEL maintainer="Timo Runge"

ARG ansible_role=${ansible_role}
ARG ansible_version=${ansible_version}
ARG TRAVIS=${TRAVIS}

ENV ansible_role=${ansible_role}
ENV travis=${TRAVIS}

RUN yum install -y epel-release
RUN yum update -y
RUN yum install -y \
    curl \
    initscripts \
    pip \
    python \
    python-pip \
    systemd \
    unzip \
    wget
RUN yum clean all

RUN echo "NETWORKING=yes" >> /etc/sysconfig/network
RUN echo "HOSTNAME=$(hostname)" >> /etc/sysconfig/network

RUN pip install --upgrade pip setuptools
RUN pip install ansible=="${ansible_version}"
RUN pip install ansible-lint coverage junit-xml splitter
RUN ansible --version

ENTRYPOINT [ "/docker/docker-entrypoint.sh" ]
