FROM centos:7
MAINTAINER Timo Runge

ARG ANSIBLE_VERSION
ARG ROLE_NAME
ARG WORKDIR

ENV ENV_ROLE_NAME=${ROLE_NAME}
ENV ENV_WORKDIR=${WORKDIR}

RUN yum install -y epel-release
RUN yum update -y
RUN yum install -y \
    curl \
    pip \
    python \
    python-pip \
    systemd
RUN yum clean all

RUN echo "NETWORKING=yes" >> /etc/sysconfig/network
RUN echo "HOSTNAME=$(hostname)" >> /etc/sysconfig/network

RUN pip install --upgrade pip setuptools
RUN pip install ansible==${ANSIBLE_VERSION}
RUN pip install ansible-lint coverage junit-xml splitter
RUN ansible --version

COPY ./ /etc/ansible/roles/${ROLE_NAME}
COPY ./docker/docker-entrypoint.sh /
COPY ./tests ${WORKDIR}

WORKDIR ${WORKDIR}

ENTRYPOINT [ "/docker-entrypoint.sh" ]
